# Generated by Django 4.1.3 on 2022-11-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RBSA_User_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('father_name', models.CharField(default='', max_length=50)),
                ('age', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=50)),
                ('about_you', models.TextField()),
                ('user_image', models.FileField(default='', upload_to='User_Images')),
                ('DOB', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
