# Generated by Django 4.1.3 on 2022-11-24 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlackHole', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RBSA_User_Form',
            new_name='RBSAUserForm',
        ),
    ]
