# Generated by Django 4.1.3 on 2022-11-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlackHole', '0003_userformpy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleUserFormOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('age', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='userformpy',
            name='user_image',
            field=models.FileField(default='', upload_to='FormsData'),
        ),
    ]
